// vue-admin-web/src/components/common/Header.vue
<template>
    <div class="header">
        <!-- 折叠按钮 -->
        <div class="collapse-btn" @click="collapseChage">
            <i class="el-icon-menu"></i>
        </div>
        <div class="logo">后台管理系统</div>
        <div class="menu-box">
            <el-menu class="el-menu-demo"
                     mode="horizontal"
                     @select="handleSelect"
                     background-color="#242f42"
                     text-color="#fff"
                     active-text-color="#1AA094">
                <el-submenu index="1">
                    <template slot="title">我的工作台</template>
                    <el-menu-item index="1-1">内容管理</el-menu-item>
                    <el-menu-item index="1-2">栏目管理</el-menu-item>
                    <el-menu-item index="1-3">权限管理</el-menu-item>
                </el-submenu>
                <el-menu-item index="2"><a href="https://www.ele.me" target="_blank">消息管理</a></el-menu-item>
            </el-menu>
        </div>
        <div class="header-right">
            <div class="header-user-con">
                <!-- 全屏显示 -->
                <div class="btn-fullscreen" @click="handleFullScreen">
                    <el-tooltip effect="dark" :content="fullscreen?`取消全屏`:`全屏`" placement="bottom">
                        <i class="el-icon-rank"></i>
                    </el-tooltip>
                </div>
                <!-- 消息中心 -->
                <div class="btn-bell">
                    <el-tooltip effect="dark" :content="message?`有${message}条未读消息`:`消息中心`" placement="bottom">
                        <router-link to="/tabs">
                            <i class="el-icon-bell"></i>
                        </router-link>
                    </el-tooltip>
                    <span class="btn-bell-badge" v-if="message"></span>
                </div>
                <!-- 用户头像 -->
                <div class="user-avator"><img src="static/img/img.jpg"></div>
                <!-- 用户名下拉菜单 -->
                <el-dropdown class="user-name" trigger="click" @command="handleCommand">
                    <span class="el-dropdown-link">
                        {{user.nickname}} <i class="el-icon-caret-bottom"></i>
                    </span>
                    <el-dropdown-menu slot="dropdown">

                        <a href="https://gitee.com/lmhc/jfinal-cms-shop/tree/master" target="_blank">
                            <el-dropdown-item>项目仓库</el-dropdown-item>
                        </a>
                        <el-dropdown-item divided  command="loginout">退出登录</el-dropdown-item>
                    </el-dropdown-menu>
                </el-dropdown>
            </div>
        </div>
    </div>
</template>
<script>
    import bus from '../common/bus';
    export default {
        data() {
            return {
                collapse: false,
                fullscreen: false,
                message: 2,
                user:{}
            }
        },
        computed:{

        },
        created:function(){
            this.user=JSON.parse(localStorage.getItem('user'));
        },
        methods:{
            // 用户名下拉菜单选择事件
            handleCommand(command) {
                if(command == 'loginout'){
                    localStorage.removeItem('ms_username')
                    this.$router.push('/login');
                }
            },
            handleSelect(index) {
                console.log(index);
                var items= [
                    {
                        icon: 'el-icon-setting',
                        index: 'dashboard',
                        title: '系统首页'
                    }
                ]
                bus.$emit('menus', items);
            },
            // 侧边栏折叠
            collapseChage(){
                this.collapse = !this.collapse;
                bus.$emit('collapse', this.collapse);
            },
            // 全屏事件
            handleFullScreen(){
                let element = document.documentElement;
                if (this.fullscreen) {
                    if (document.exitFullscreen) {
                        document.exitFullscreen();
                    } else if (document.webkitCancelFullScreen) {
                        document.webkitCancelFullScreen();
                    } else if (document.mozCancelFullScreen) {
                        document.mozCancelFullScreen();
                    } else if (document.msExitFullscreen) {
                        document.msExitFullscreen();
                    }
                } else {
                    if (element.requestFullscreen) {
                        element.requestFullscreen();
                    } else if (element.webkitRequestFullScreen) {
                        element.webkitRequestFullScreen();
                    } else if (element.mozRequestFullScreen) {
                        element.mozRequestFullScreen();
                    } else if (element.msRequestFullscreen) {
                        // IE11
                        element.msRequestFullscreen();
                    }
                }
                this.fullscreen = !this.fullscreen;
            }
        },
        mounted(){
            if(document.body.clientWidth < 1500){
                this.collapseChage();
            }
        }
    }
</script>
<style scoped>
    .header {
        position: relative;
        box-sizing: border-box;
        width: 100%;
        height: 70px;
        font-size: 22px;
        color: #fff;
    }
    .collapse-btn{
        float: left;
        padding: 0 21px;
        cursor: pointer;
        line-height: 70px;
    }
    .header .logo{
        float: left;
        width:150px;
        line-height: 70px;
    }
    .header .menu-box{
        float: left;
    }
    .header-right{
        float: right;
        padding-right: 50px;
    }
    .header-user-con{
        display: flex;
        height: 70px;
        align-items: center;
    }
    .btn-fullscreen{
        transform: rotate(45deg);
        margin-right: 5px;
        font-size: 24px;
    }
    .btn-bell, .btn-fullscreen{
        position: relative;
        width: 30px;
        height: 30px;
        text-align: center;
        border-radius: 15px;
        cursor: pointer;
    }
    .btn-bell-badge{
        position: absolute;
        right: 0;
        top: -2px;
        width: 8px;
        height: 8px;
        border-radius: 4px;
        background: #f56c6c;
        color: #fff;
    }
    .btn-bell .el-icon-bell{
        color: #fff;
    }
    .menu-box{
        height: 70px;
    }
    .user-name{
        margin-left: 10px;
    }
    .user-avator{
        margin-left: 20px;
    }
    .user-avator img{
        display: block;
        width:40px;
        height:40px;
        border-radius: 50%;
    }
    .el-dropdown-link{
        color: #fff;
        cursor: pointer;
    }
    .el-dropdown-menu__item{
        text-align: center;
    }
</style>

// src/app/header/header.component.ts
<div class="header">
  <div class="collapse-btn" (click)="collapseChange();">
    <i class="el-icon-menu"></i>
  </div>
  <div class="logo">后台管理系统</div>
  <div class="menu-box">
    <el-menu class="el-menu-demo"
      mode="horizontal"
      (select)="handleSelect($event);"
      backgroundColor="#242f42"
                 textColor="#fff"
                 activeTextColor="#1AA094">
            <el-submenu *ngFor="let item of items; let i = index" [index]="'menu_'+item.lanmuId">
                <template #title>
                    <i [class]="item.icon"></i><span>{{ item.title }}</span>
                </template>
                <el-menu-item *ngFor="let subItem of item.subs" [index]="'menu_'+subItem.lanmuId" [route]="{ path: '/'+subItem.index,query:{lanmuId:subItem.lanmuId,title:subItem.title}}">
                    {{ subItem.title }}
                </el-menu-item>
            </el-submenu>
        </el-menu>
    </div>
    <div class="header-right">
        <div class="header-user-con">
            <div class="btn-fullscreen" (click)="handleFullScreen()">
                <el-tooltip effect="dark" [content]="fullscreen?'取消全屏':'全屏'" placement="bottom">
                    <i class="el-icon-rank"></i>
                </el-tooltip>
            </div>
            <div class="btn-bell">
                <el-tooltip effect="dark" [content]="message?'有'+message+'条未读消息':'消息中心'" placement="bottom">
                    <a routerLink="/tabs">
                        <i class="el-icon-bell"></i>
                    </a>
                </el-tooltip>
                <span class="btn-bell-badge" *ngIf="message"></span>
            </div>
            <div class="user-avator"><img src="static/img/img.jpg"></div>
            <el-dropdown class="user-name" trigger="click" (command)="handleCommand($event)">
                <span class="el-dropdown-link">
                    {{user.nickname}} <i class="el-icon-caret-bottom"></i>
                </span>
                <el-dropdown-menu #dropdown>
                    <a href="https://gitee.com/lmhc/jfinal-cms-shop/tree/master" target="_blank">
                        <el-dropdown-item>项目仓库</el-dropdown-item>
                    </a>
                    <el-dropdown-item divided  command="loginout">退出登录</el-dropdown-item>
                </el-dropdown-menu>
            </el-dropdown>
        </div>
    </div>
</div>
</new_file>

<new_file file_path="src/app/header/header.component.ts">
import { Component, OnInit } from '@angular/core';
import { BusService } from '../bus.service';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.css'],
})
export class HeaderComponent implements OnInit {
  collapse: boolean = false;
  fullscreen: boolean = false;
  message: number = 2;
  user: any = {};

  constructor(private busService: BusService) {}

  ngOnInit(): void {
    this.user = JSON.parse(localStorage.getItem('user'));
  }

  handleCommand(command: string) {
    if (command === 'loginout') {
      localStorage.removeItem('ms_username');
      this.router.navigate(['/login']);
    }
  }

  handleSelect(index: string) {
    console.log(index);
    var items = [
      {
        icon: 'el-icon-setting',
        index: 'dashboard',
        title: '系统首页',
      },
    ];
    this.busService.emit('menus', items);
  }

  collapseChange() {
    this.collapse = !this.collapse;
    this.busService.emit('collapse', this.collapse);
  }

  handleFullScreen() {
    let element = document.documentElement;
    if (this.fullscreen) {
      if (document.exitFullscreen) {
        document.exitFullscreen();
      } else if (document.webkitCancelFullScreen) {
        document.webkitCancelFullScreen();
      } else if (document.mozCancelFullScreen) {
        document.mozCancelFullScreen();
      } else if (document.msExitFullscreen) {
        document.msExitFullscreen();
      }
    } else {
      if (element.requestFullscreen) {
        element.requestFullscreen();
      } else if (element.webkitRequestFullScreen) {
        element.webkitRequestFullScreen();
      } else if (element.mozRequestFullScreen) {
        element.mozRequestFullScreen();
      } else if (element.msRequestFullscreen) {
        element.msRequestFullscreen();
      }
    }
    this.fullscreen = !this.fullscreen;
  }
}
